const db = require('./connection');
const { User, Product, Category, Modifiers } = require('../models');

db.once('open', async () => {
  await Category.deleteMany();

  const categories = await Category.insertMany([
    { name: 'Pizzas' },
    { name: 'Rolled or Folded Pizza'},
    { name: 'Appetizers' },
    { name: 'Dinners' },
    { name: 'Pasta Favorites' },
    { name: 'Salads' },
    { name: 'Hot Subs' },
    { name: 'Cold Subs'},
    { name: 'Side Orders' },
    { name: 'Desserts' },
    { name: 'Beverages' },
    { name: 'Drakes Cakes' },
    { name: 'NY Specialties' },
  ]);

  const logo = 'buonos-logo.png'; 
  console.log('categories seeded');

  await Product.deleteMany();

  const products = await Product.insertMany([
    //* Pizzas
    { name: 'Neapolitin Pizza',
      description: 'Naples-style pizza, thin crust made with tomato sauce and mozzarella cheese',
      image: logo,
      price: '15.49',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Sicillian Pizza',
      description: 'Sicily-style pizza, bread cooked on a square pan. Its dough recipe is heftier, with twice as much flour and water and three times as much yeast.',
      image: logo,
      price: '16.99',
      quantity: 200,
      category: categories[0]._id,
    },
    // Specialty Pizzas
    { name: 'White Pizza',
      description: 'Delicious blend of garlic butter & ricotta Cheese covered with whole milk mozzarella.',
      image: logo,
      price: '16.99',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Veggie Pizza',
      description: 'Mushrooms, olives, green bell peppers, and onions.',
      image: logo,
      price: '23.99',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Margherita The Buonos Way',
      description: 'Fresh mozzarella, tomato puree, basil puree & olive oil.',
      image: logo,
      price: '16.49',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Meat Lovers Pizza',
      description: 'Pepperoni, sausage, meatballs, and bacon.',
      image: logo,
      price: '23.99',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Ziti Pizza',
      description: 'Topped with mozzarella cheese, ricotta, and ziti pasta',
      image: logo,
      price: '25.99',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'The Works aka Supreme Pizza',
      description: 'Pepperoni, sausage, mushrooms, green bell peppers, and onions.',
      image: logo,
      price: '26.99',
      quantity: 200,
      category: categories[0]._id,
    },
    // Pizza gluten free
    { name: 'Gluten Free Pizza',
      description: '',
      image: logo,
      price: '13.49',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Cauliflower Crust Gluten Free Pizza',
      description: '',
      image: logo,
      price: '13.49',
      quantity: 200,
      category: categories[0]._id,
    },
    // Pizza ny the slice
    { name: 'Neapolitan Cheese Slice',
      description: '',
      image: logo,
      price: '2.99',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'Sicilain Cheese Slice',
      description: '',
      image: logo,
      price: '3.49',
      quantity: 200,
      category: categories[0]._id,
    },
    { name: 'White Cheese Slice',
      description: '',
      image: logo,
      price: '3.49',
      quantity: 200,
      category: categories[0]._id,
    },
    //* Rolled or Folded Pizza
    //!Category?
    { name: 'Sausage Roll',
      description: 'New Yorks famous tasty blend of sausage peppers onions & mozzarell baked together in a rolled pizza dough.',
      image: logo,
      price: '7.99',
      quantity: 200,
      category: categories[1]._id,
    },
    { name: 'Calzone',
      description: 'Ricotta & mozzarella, baked together in a folded pizza dough.',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[1]._id,
    },
    // Stromboli
    { name: 'Meatball',
      description: 'Meatballs marinara & mozzarella baked together in a rolled pizza dough.',
      image: logo,
      price: '10.99',
      quantity: 200,
      category: categories[1]._id,
    },
    { name: 'Sausage Peppers Onions',
      description: 'Sausage green bell peppers onions and mozzarella baked together in a rolled pizza dough.',
      image: logo,
      price: '13.99',
      quantity: 200,
      category: categories[1]._id,
    },
    { name: 'Eggplant',
      description: 'Eggplant cutlets marinara & mozzarella baked together in a rolled pizza dough.',
      image: logo,
      price: '13.99',
      quantity: 200,
      category: categories[1]._id,
    },
    { name: 'Pepperoni Sausage Meatball',
      description: 'Pepperoni sausage meatballs marinara & mozzarella baked together in a rolled pizza dough.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[1]._id,
    },
    { name: 'Chicken',
      description: 'Chicken cutlet marinara & mozzarella baked together in a rolled pizza dough.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[1]._id,
    },
    { name: 'Salami Capicola Soppressata',
      description: 'Salami capicola sorppressata marinara & mozzarella baked together in a rolled pizza dough.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[1]._id,
    },
    //* Appetizers
    { name: 'French Fries',
      description: 'Our delicious French fries are deep-fried, till golden brown, with a crunchy exterior.',
      image: logo,
      price: '3.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Garlic Bread',
      description: 'Bread, topped with garlic, herb seasoning, baked to perfection.',
      image: logo,
      price: '3.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Sicilian Garlic Bread',
      description: 'Garlic Bread with melted mozzarella.',
      image: logo,
      price: '4.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Meatballs and ricotta',
      description: 'Twin meatballs in tomato sauce topped with dollups of ricotta.',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Meatball Sliders',
      description: 'Five piece crostini topped with meatballs, tomato sauce, and melty mozzarella.',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Boneless Chicken Wings',
      description: 'Hot, medium, mild, BBQ, honey hot, honey BBQ. Side of ranch or blue cheese.',
      image: logo,
      price: '7.25',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Chicken Wings',
      description: 'Hot, medium, mild, BBQ, honey hot, honey BBQ. Side of ranch or blue cheese.',
      image: logo,
      price: '7.25',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Pepperoni Pizza Fries',
      description: 'Fries, mozzarella, pepperoni, with marinara sauce.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Fried Ravioli',
      description: 'Six piece bite size ravioli stuffed with ricotta served with marinara.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Fried Mushrooms',
      description: 'Battered and deep fried, served with ranch.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Fried Zucchini',
      description: 'Battered and deep fried, served with ranch.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[2]._id,
    },
    { name: 'Fried Mozzrella Sticks',
      description: 'Battered and deep fried, served with marinara.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[2]._id,
    },
    // Spec
    //! { name: 'Arancini',
    //!   description: 'Deep fried rissotto rice balls stuffed with meat-sauce and green peas, served with marinara.',
    //!   image: 'buonos-logo-transparent.png',
    //!   price: '10.99',
    //!   quantity: 200,
    //!   category: categories[2]._id,
    //! },
    //* Dinners
    { name: 'Stuffed Shells',
      description: 'Classic ricotta stuffed shells with flavorful three cheese ricotta filling and delicious marinara sauce.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[3]._id,
    },
    { name: 'Baked Penne',
      description: '',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[3]._id,
    },
    { name: 'Manicotti',
      description: 'A large tube of fresh pasta stuffed with a blend of soft cheese.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[3]._id,
    },
    { name: 'Lasagna',
      description: 'Stacked layers of pasta packed with meat and cheese, covered in our own home made sauce.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[3]._id,
    },
    { name: 'Jumbo Ravioli',
      description: 'Six jumbo sized ricotta stuffed ravioli topped with marinara.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Eggplant Parmigiana',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '17.99',
      quantity: 200,
      category: categories[3]._id,
    },
    { name: 'Chicken Parmigiana',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '17.99',
      quantity: 200,
      category: categories[3]._id,
    },
    //* Pastas Favorites
    { name: 'Butter Sauce',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '8.49',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Tomato Sauce',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '9.49',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Garlic & Oil',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '9.49',
      quantity: 200,
      category: categories[4]._id,
    },
    // Pasta Plus
    { name: 'Pasta With Meatballs',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Pasta With Meat Sauce',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Pasta With Sausage',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Pasta With White Clam Sauce',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[4]._id,
    },
    { name: 'Pasta With Red Clam Sauce',
      description: 'Served with choice of spaghetti or penne.',
      image: logo,
      price: '14.99',
      quantity: 200,
      category: categories[4]._id,
    },
    //* Salads
    { name: 'Caesar',
      description: 'Romaine lettuce, croutons, shredded parmesan & caesar dressing.',
      image: logo,
      price: '5.25',
      quantity: 200,
      category: categories[5]._id,
    },
    { name: 'House Toss',
      description: 'Romaine lettuce, tomatoes, onions, olives, romano cheese & oregano.',
      image: logo,
      price: '5.25',
      quantity: 200,
      category: categories[5]._id,
    },
    { name: 'Caprese',
      description: 'Fresh mozzarella, tomatoes, basil, olive oil & balsamic glaze.',
      image: logo,
      price: '8.49',
      quantity: 200,
      category: categories[5]._id,
    },
    { name: 'Antipasto',
      description: 'Romaine lettuce, tomatoes, capicola, provolone, salami, onions, giardiniera, olives & oregano.',
      image: logo,
      price: '11.99',
      quantity: 200,
      category: categories[5]._id,
    },
    { name: 'Chef',
      description: 'Romaine lettuce, tomatoes, ham, provolone, onions, banana peppers, olives & oregano.',
      image: logo,
      price: '11.99',
      quantity: 200,
      category: categories[5]._id,
    },
    { name: 'Chicken Cutlet',
      description: 'Romaine lettuce, tomatoes, deep fried chicken cutlet, onions, banana peppers, olives & oregano.',
      image: logo,
      price: '11.99',
      quantity: 200,
      category: categories[5]._id,
    },
    //* Hot Subs
    { name: 'Pepperoni Melt',
      description: '',
      image: logo,
      price: '7.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Sausage Peppers & Onions',
      description: '',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Meatball Parmigiana',
      description: '',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Sausage Parmigiana',
      description: '',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Chicken Parmigiana',
      description: 'Fried chicken breast, marinara sauce, and mozzarella cheese.',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Eggplant Parmigiana',
      description: '',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Chicken Philly',
      description: '',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[6]._id,
    },
    { name: 'Steak Philly',
      description: '',
      image: logo,
      price: '10.99',
      quantity: 200,
      category: categories[6]._id,
    },
    //* Cold Subs
    { name: 'Ham & Cheese',
      description: 'Classic ham and cheese.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[7]._id,
    },
    { name: 'Salami & Provalone',
      description: '',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[7]._id,
    },
    { name: 'Pepperoni & Provalone',
      description: '',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[7]._id,
    },
    { name: 'Capicola & Provalone',
      description: '',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[7]._id,
    },
    { name: 'Mortadella',
      description: 'Mortadella fresh mozzarella roasted red peppers balsamic glaze.',
      image: logo,
      price: '8.99',
      quantity: 200,
      category: categories[7]._id,
    },
    { name: 'Italian Mix',
      description: 'Ham, salami, capicola, onions, sweet peppers, and cheese.',
      image: logo,
      price: '9.99',
      quantity: 200,
      category: categories[7]._id,
    },
    //* Side Orders
    { name: 'Spaghetti',
      description: '',
      image: logo,
      price: '4.99',
      quantity: 200,
      category: categories[8]._id,
    },
    { name: 'Meatballs',
      description: '',
      image: logo,
      price: '4.99',
      quantity: 200,
      category: categories[8]._id,
    },
    { name: 'Sausage',
      description: '',
      image: logo,
      price: '4.99',
      quantity: 200,
      category: categories[8]._id,
    },
    { name: 'Spaghetti & Meatball',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[8]._id,
    },
    //* Desserts
    { name: 'Black & White Cookie',
      description: 'A NY CLASSIC...All Black & Whites are made in Queens NYC',
      image: logo,
      price: '3.75',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Large Cannoli',
      description: 'Large Cannoli with or without pistachios. Delicious tube of fried dough, filled with a sweet, creamy ricotta filling.',
      image: logo,
      price: '5.49',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Tiramisu',
      description: 'A delicious coffee-flavored Italian dessert. Whipped mixture of eggs, sugar & mascarpone cheese, flavored with cocoa. Choice of plain, chocolate, carmel or strawberry syrup topping.',
      image: logo,
      price: '6.49',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Limoncello Cake',
      description: 'Limoncello mascarpone cake. Choice of plain, chocolate, carmel or strawberry syrup topping',
      image: logo,
      price: '6.49',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Crumb Cake',
      description: 'Another NY classic now available here. Our crumb cake is also made in Queens NYC',
      image: logo,
      price: '4.50',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Zeppoli',
      description: 'Delicious Fried Dough with powered sugar. Crispy on the outside, yet light and fluffy on the inside. These mini Italian donut holes will become your new fave',
      image: logo,
      price: '6.49',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Cheese Cake',
      description: 'Classic cheesecake with a rich, dense, smooth, and creamy consistency.',
      image: logo,
      price: '6.49',
      quantity: 200,
      category: categories[9]._id,
    },
    { name: 'Chocolate Mousse Cake',
      description: 'Chocolate mousse cake. Choice of plain, chocolate, carmel or strawberry syrup topping',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[9]._id,
    },
    //* Berverages (+beer/wine)
    { name: 'Fountain Soda or Ice Tea',
      description: '20 oz',
      image: logo,
      price: '2.75',
      quantity: 200,
      category: categories[10]._id,
    },
    { name: '2 Liter Bottle Soda',
      description: '',
      image: logo,
      price: '3.99',
      quantity: 200,
      category: categories[10]._id,
    },
    { name: 'Dr Brown Soda Can',
      description: 'A NY classic',
      image: logo,
      price: '2.50',
      quantity: 200,
      category: categories[10]._id,
    },
    { name: 'Bottled Water',
      description: '',
      image: logo,
      price: '1.99',
      quantity: 200,
      category: categories[10]._id,
    },
    //! size
    { name: 'Yoo-Hoo',
      description: '12 oz bottle',
      image: logo,
      price: '2.99',
      quantity: 200,
      category: categories[10]._id,
    },
    //! size
    { name: 'Bottled soda',
      description: '',
      image: logo,
      price: '2.99',
      quantity: 200,
      category: categories[10]._id,
    },
    //! size
    { name: 'Bottles Tea',
      description: '',
      image: logo,
      price: '2.99',
      quantity: 200,
      category: categories[10]._id,
    },
    //! size
    { name: 'AZ Lemonade',
      description: '',
      image: logo,
      price: '5.99',
      quantity: 200,
      category: categories[10]._id,
    },
    //! test price
    { name: 'Beer & Wine',
      description: 'Available in store ONLY!',
      image: logo,
      price: '10.99',
      quantity: 200,
      category: categories[10]._id,
    },
    //* Drakes Cakes
    //! item count
    { name: 'Devil Dogs',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    { name: 'Coffe Cakes',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    { name: 'Yankee Doodles',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    { name: 'Yodels',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    { name: 'Funny Bones',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    { name: 'Ring Dings',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    { name: 'Fruity Pies',
      description: '',
      image: logo,
      price: '6.99',
      quantity: 200,
      category: categories[11]._id,
    },
    //* NY Specialies
    { name: 'Gabilas Coney Island Potato Knish',
      description: '',
      image: logo,
      price: '3.50',
      quantity: 200,
      category: categories[12]._id,
    },
    { name: 'Mikes Hot Sauce',
      description: 'Bottled.',
      image: logo,
      price: '10.00',
      quantity: 200,
      category: categories[12]._id,
    },
    // Angelo's
    { name: 'Pint Gelato',
      description: 'Pint.',
      image: logo,
      price: '5.50',
      quantity: 200,
      category: categories[12]._id,
    },
    { name: 'Italian Ice 5oz',
      description: '5 oz',
      image: logo,
      price: '1.50',
      quantity: 200,
      category: categories[12]._id,
    },
    { name: 'Italian Ice 9oz',
      description: '9 oz',
      image: logo,
      price: '3.50',
      quantity: 200,
      category: categories[12]._id,
    },
    { name: 'Italian Ice Pint',
      description: 'Pint',
      image: logo,
      price: '4.50',
      quantity: 200,
      category: categories[12]._id,
    },
  ]);

  console.log('products seeded');

  //#region Modifier Data
  const regularPizzaToppingPriceWhole = 2.75;
  const regularPizzaToppingPriceHalf = 1.39;

  const premiumPizzaToppingPriceWhole = 5.25;
  const premiumPizzaToppingPriceHalf = 2.65;

  const regularCalzoneFillingsPriceSmall = 1.49;
  const regularCalzoneFillingsPriceLarge = 1.99;

  const premiumCalzoneFillingsPriceSmall = 2.50;
  const premiumCalzoneFillingsPriceLarge = 3.25;

  const regularSliceToppingPrice = .75; 
  const premiumSliceToppingPrice = 1.50;
  
  const quantity = 200;
  //#endregion

  await Modifiers.deleteMany();

  const modifiers = await Modifiers.insertMany([
    // Regular Pizza Whole
    { name: 'Anchovy-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Bacon-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Banana-Peppers-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Basil-Puree-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Green-Bell-Peppers-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Broccoli-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Cappicola-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Garlic-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Ham-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Jalapenos-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Meatballs-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Mushrooms-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Olives-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Onions-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Pepperoni-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Pepperoncini-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Pineapple-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Roasted Red Pepper-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Sausage-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Spinach-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Salami-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Tomato-Regular-Pizza-Whole',
      price: regularPizzaToppingPriceWhole,
      quantity: quantity,
    },
    // Premium Pizza Whole
    { name: 'Chicken Cutlet-Regular-Pizza-Whole',
      price: premiumPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Clams-Regular-Pizza-Whole',
      price: premiumPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Eggplant-Regular-Pizza-Whole',
      price: premiumPizzaToppingPriceWhole,
      quantity: quantity,
    },
    { name: 'Soppressata-Regular-Pizza-Whole',
      price: premiumPizzaToppingPriceWhole,
      quantity: quantity,
    },
    // Regular Pizza Half
    { name: 'Anchovy-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Bacon-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Banana Peppers-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'BasilPuree-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'GreenBellPeppers-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Broccoli-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Cappicola-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Garlic-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Ham-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Jalapenos-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Meatballs-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Mushrooms-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Olives-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Onions-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Pepperoni-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Pepperoncini-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Pineapple-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Roasted Red Pepper-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Sausage-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Spinach-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Salami-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Tomato-Regular-Pizza-Half',
      price: regularPizzaToppingPriceHalf,
      quantity: quantity,
    },
    // Premium Pizza Half
    { name: 'Chicken-Cutlet-Premuim-Pizza-Half',
      price: premiumPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Clams-Premuim-Pizza-Half',
      price: premiumPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Eggplant-Premuim-Pizza-Half',
      price: premiumPizzaToppingPriceHalf,
      quantity: quantity,
    },
    { name: 'Soppressata-Premuim-Pizza-Half',
      price: premiumPizzaToppingPriceHalf,
      quantity: quantity,
    },
    // Regular Calzones Small
    { name: 'Anchovy-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Bacon-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Banana Peppers-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'BasilPuree-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'GreenBellPeppers-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Broccoli-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Cappicola-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Garlic-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Ham-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Jalapenos-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Meatballs-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Mushrooms-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Olives-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Onions-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Pepperoni-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Pepperoncini-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Pineapple-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Roasted Red Pepper-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Sausage-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Spinach-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Salami-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Tomato-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    // Premium Calzones Small
    { name: 'Chicken-Cutlet-Premium-Small',
      price: premiumCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Clams-Premium-Small',
      price: premiumCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Eggplant-Cutlet-Premium-Small',
      price: premiumCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    { name: 'Soppressata-Premium-Small',
      price: premiumCalzoneFillingsPriceSmall,
      quantity: quantity,
    },
    // Regular Calzones Large
    { name: 'Anchovy-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Bacon-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Banana Peppers-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'BasilPuree-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'GreenBellPeppers-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Broccoli-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Cappicola-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Garlic-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Ham-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Jalapenos-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Meatballs-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Mushrooms-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Olives-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Onions-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Pepperoni-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Pepperoncini-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Pineapple-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Roasted Red Pepper-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Sausage-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Spinach-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Salami-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Tomato-Regular-Calzone-Small',
      price: regularCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    // Premium Calzones Large
    { name: 'Chicken-Cutlet-Premium-Small',
      price: premiumCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Clams-Premium-Small',
      price: premiumCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Eggplant-Cutlet-Premium-Small',
      price: premiumCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    { name: 'Soppressata-Premium-Small',
      price: premiumCalzoneFillingsPriceLarge,
      quantity: quantity,
    },
    // Regular Slice
    { name: 'Anchovy-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Bacon-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Banana Peppers-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'BasilPuree-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'GreenBellPeppers-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Broccoli-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Cappicola-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Garlic-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Ham-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Jalapenos-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Meatballs-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Mushrooms-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Olives-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Onions-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Pepperoni-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Pepperoncini-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Pineapple-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Roasted Red Pepper-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Sausage-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Spinach-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Salami-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Tomato-Regular-Calzone-Small',
      price: regularSliceToppingPrice,
      quantity: quantity,
    },
    // Premium Slice 
    { name: 'Chicken-Cutlet-Premium-Small',
      price: premiumSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Clams-Premium-Small',
      price: premiumSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Eggplant-Cutlet-Premium-Small',
      price: premiumSliceToppingPrice,
      quantity: quantity,
    },
    { name: 'Soppressata-Premium-Small',
      price: premiumSliceToppingPrice,
      quantity: quantity,
    },
    // Extras
    { name: 'Ranch Dressing',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Blue Cheese Dressing',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Italian Dressing',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Hot Sauce',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Medium Sauce',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Mild Sauce',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Honey Hot',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'BBQ',
      price: 0.75,
      quantity: quantity,
    },
    { name: 'Honey BBQ',
      price: 0.75,
      quantity: quantity,
    },
  ]);

  console.log('modifiers seeded');

  await User.deleteMany();

  await User.create({
    firstName: 'Pamela',
    lastName: 'Washington',
    email: 'pamela@testmail.com',
    password: 'password12345',
    orders: [
      {
        products: [products[0]._id, products[0]._id, products[1]._id]
      }
    ]
  });

  await User.create({
    firstName: 'Elijah',
    lastName: 'Holt',
    email: 'eholt@testmail.com',
    password: 'password12345'
  });

  console.log('users seeded');

  process.exit();
});